version: '3.9'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '4000:4000'
  summer:
    build:
      dockerfile: Dockerfile
      context: ./kount-sum
    ports:
      - '5000:5000'
  front:
    build:
      dockerfile: Dockerfile
      context: ./kount-front
    ports:
      - '80:80'
    links:
      - api
