# Environment
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8ount-env-map
data:
  history: 'Saved!!!'
---
# Persistent Storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8ount-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
---
# Storage Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8ount-pvc
spec:
  volumeName: k8ount-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
# Services
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: clj-k8ount
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000
      name: api
    - protocol: 'TCP'
      port: 80
      targetPort: 80
      name: front
    - protocol: 'TCP'
      port: 5000
      targetPort: 5000
      name: sum
    - protocol: 'TCP'
      port: 6000
      targetPort: 6000
      name: history
  type: LoadBalancer
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clj-k8ount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clj-k8ount
  template:
    metadata:
      labels:
        app: clj-k8ount
    spec:
      containers:
        - name: api
          image: solar7455/kub-k8ount-api
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 15
            initialDelaySeconds: 5
        - name: front
          image: solar7455/kub-k8ount-front
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 15
            initialDelaySeconds: 5
        - name: sum
          image: solar7455/kub-k8ount-sum
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 15
            initialDelaySeconds: 5
        - name: history
          image: solar7455/kub-k8ount-history:latest
          env:
            - name: HISTORY_TIMESTAMP
              valueFrom:
                configMapKeyRef:
                  name: k8ount-env-map
                  key: history
          livenessProbe:
            httpGet:
              path: /health
              port: 6000
            periodSeconds: 15
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /src
              name: history-vol
      volumes:
        - name: history-vol
          persistentVolumeClaim:
            claimName: k8ount-pvc
