name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2021.09.15'
    - uses: DeLaGuardo/setup-clojure@3.5
      with:
        tools-deps: '1.10.3.981'
    - name: Run checks for api
      run: make checks
    - name: Run tests for api
      run: make test
    - name: Run tests for summer
      run: cd kount-sum && make test
    - name: Run tests for history
      run: cd kount-history && make test
